#k8s scheduler 启动文件
#
scheduler_develop:
  restart: always
  image: docker.weibangong.me/google-containers/hyperkube:v1.5.2
  net: host
  volumes:
  - /home/docker/app/kubernetes/logs/scheduler/:/var/log/kube/scheduler/
  command: ./scheduler --master=http://172.16.35.135:8089 --logtostderr=false
                       --log-dir=/var/log/kube/scheduler/ --v=2
#